# Generated by Django 3.2.8 on 2021-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telugu_marks', models.IntegerField()),
                ('hindi_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('maths_marks', models.IntegerField()),
                ('science_marks', models.IntegerField()),
                ('social_marks', models.IntegerField()),
            ],
        ),
    ]
