# Generated by Django 3.2.8 on 2021-10-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.TextField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
