# Generated by Django 3.2.8 on 2021-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='att_classes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='total_classes',
            field=models.IntegerField(default=58),
            preserve_default=False,
        ),
    ]
