# Generated by Django 3.2.8 on 2021-10-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211016_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
