# Generated by Django 3.2.9 on 2021-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='english_marks',
            new_name='english_final_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hindi_marks',
            new_name='english_mid_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='maths_marks',
            new_name='hindi_final_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='science_marks',
            new_name='hindi_mid_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='social_marks',
            new_name='maths_final_marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='telugu_marks',
            new_name='maths_mid_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='science_final_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='science_mid_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='social_final_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='social_mid_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='telugu_final_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='telugu_mid_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
